name: Deploy MERN App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            rm -rf mern-app || true
            git clone https://github.com/Laphtrahddis/expressit_live.git mern-app
            cd mern-app
            docker-compose down || true
            docker-compose build
            docker-compose up -d --remove-orphans
