name: Deploy MERN App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
              # 🔥 Kill everything properly
              docker compose down --volumes --remove-orphans || true

              # 🔥 Delete all unused Docker stuff (including old images/containers)
              docker system prune -a -f

              # ✅ Clean clone your repo
              sudo rm -rf mern-app || true
              git clone https://github.com/Laphtrahddis/expressit_live.git mern-app
              cd mern-app

              # 🚀 Rebuild and run fresh containers
              docker compose build --no-cache
              docker compose up -d --remove-orphans


